[package]
name = "day_12"
version = "0.1.0"
authors = ["Matt Mullins <mmullins@mmlx.us>"]
edition = "2018"

[dependencies]
nom = "4.1.1"
itertools = "0.8.0"
rayon = "1.0"
log = "0.4.6"
env_logger = "0.6.0"
